In [1]:
import numpy as np

In [22]:
n = 10
list_3n = np.random.randint(1, 100, 3*n)

In [23]:
list_3n

array([54, 32, 93, 81,  9, 83, 91, 73, 18, 49, 55, 77, 12, 15, 12, 89, 68,
       85, 44, 23, 25, 48, 57, 94, 25, 92, 17, 90, 26, 23])

In [24]:
list_3n_sorted = np.sort(list_3n)
list_3n_sorted

array([ 9, 12, 12, 15, 17, 18, 23, 23, 25, 25, 26, 32, 44, 48, 49, 54, 55,
       57, 68, 73, 77, 81, 83, 85, 89, 90, 91, 92, 93, 94])

In [32]:
# Create triplets
(list_3n_sorted[0], list_3n_sorted[-2], list_3n_sorted[-1])

(9, 93, 94)

In [30]:
list_3n_sorted = list_3n_sorted[1:-2]
list_3n_sorted

array([12, 12, 15, 17, 18, 23, 23, 25, 25, 26, 32, 44, 48, 49, 54, 55, 57,
       68, 73, 77, 81, 83, 85, 89, 90, 91, 92])

In [33]:
list_3n_sorted = np.sort(list_3n)
tuples_list = []
while True:
    tuples_list.append((list_3n_sorted[0], list_3n_sorted[-2], list_3n_sorted[-1]))
    list_3n_sorted = list_3n_sorted[1:-2]
    if len(list_3n_sorted) == 0:
        break

In [34]:
tuples_list

[(9, 93, 94),
 (12, 91, 92),
 (12, 89, 90),
 (15, 83, 85),
 (17, 77, 81),
 (18, 68, 73),
 (23, 55, 57),
 (23, 49, 54),
 (25, 44, 48),
 (25, 26, 32)]